# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 04:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminateTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipContent', models.TextField(default='\u65e0', max_length=500, verbose_name='\u5185\u5bb9')),
                ('submitTime', models.DateTimeField(default=datetime.datetime(2016, 9, 3, 4, 44, 13, 558000, tzinfo=utc), verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('theExaminer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u5ba1\u67e5\u539f\u5219\u53ca\u6280\u5de7',
                'verbose_name_plural': '\u5ba1\u67e5\u539f\u5219\u53ca\u6280\u5de7',
            },
        ),
        migrations.CreateModel(
            name='TipCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(default='\u65e0', max_length=20, verbose_name='\u5ba1\u67e5\u65b9\u9762')),
            ],
            options={
                'verbose_name': '\u5ba1\u67e5\u6d89\u53ca\u6cd5\u6761\u53ca\u95ee\u9898\u7684\u7c7b\u578b',
                'verbose_name_plural': '\u5ba1\u67e5\u6d89\u53ca\u6cd5\u6761\u53ca\u95ee\u9898\u7684\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='examinatetip',
            name='tipCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinatetips.TipCategory'),
        ),
    ]
