# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinatetips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinatetip',
            name='submitTime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='examinatetip',
            name='tipCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examinatetips.TipCategory'),
        ),
    ]
